### ISSUE TITLE
Errors when deleting commands that are in a guild

### ISSUE THREAD

**Issue by Blockzilla101** [JeroenoBoy/SlashDiscord.js#1]
When `handler.deleteUnregisteredCommands` is set to `true` it cant delete commands that are inside guilds. This maybe because of the missing guild paramater [here](https://github.com/JeroenoBoy/SlashDiscord.js/blob/main/src/SlashGuild.ts#L73).
Stack Trace:
```
ResponseError: Error while making request: Unknown application command
    at SlashCommandHandler.checkFetchError (/storage/projects/Botzilla/node_modules/slashdiscord.js/dist/SlashCommandHandler.js:204:23)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async SlashCommandHandler.deleteCommand (/storage/projects/Botzilla/node_modules/slashdiscord.js/dist/SlashCommandHandler.js:165:9)
    at async SlashGuild.load (/storage/projects/Botzilla/node_modules/slashdiscord.js/dist/SlashGuild.js:40:21)
    at async SlashCommandHandler.start (/storage/projects/Botzilla/node_modules/slashdiscord.js/dist/SlashCommandHandler.js:69:13) 
```
When I try to manually delete them it throws a 404 not found (malformed request?)
```
ResponseError: Error while making request: 404: Not Found
    at SlashCommandHandler.checkFetchError (/storage/projects/Botzilla/node_modules/slashdiscord.js/dist/SlashCommandHandler.js:204:23)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async SlashCommandHandler.deleteCommand (/storage/projects/Botzilla/node_modules/slashdiscord.js/dist/SlashCommandHandler.js:165:9) 
```
slashdiscord.js version: `1.0.10`
node version: `15.8.0`

**Comment by JeroenoBoy** [comment]
i will be looking further into it, thanks for reporting

**Comment by MBarnulf** [comment]
(I had the same issue today)

**Comment by JeroenoBoy** [comment]
Could you send me the error?

**Comment by MBarnulf** [comment]
(sorry, I figured that in my case, the issue was in my code)
